### ISSUE TITLE
Free API key !=Free access to API

### ISSUE THREAD

**Issue by thomashrabe** [0xacx/chatGPT-shell-cli#105]
Thanks for creating the script. 
However, I am failing with
![image](https://user-images.githubusercontent.com/3632672/236931370-01a17031-130a-49d4-a6fd-5c28396a8252.png)

because I do not have a pay OpenAI account it tells me 

```
me@localhost:~$ chatgpt.sh
Welcome to chatgpt. You can quit with 'exit' or 'q'.

Enter a prompt:
what is the radius of earth

Your request to Open AI API failed: insufficient_quota
You exceeded your current quota, please check your plan and billing details.
```

**Comment by 0xacx** [comment]
Well, as the message says "You exceeded your current quota, please check your plan and billing details". 
Have you checked your OpenAI API usage? Your key has probably expired.

**Comment by thomashrabe** [comment]
To be more specific, I just had signed up for an openai account yesterday. I saw free but what it in fact means you need to add a payment method and probably get a free quota before it taps into your funds… I understand this is off topic, but Free as written in the readme is little bit misleading :)

**Comment by thomashrabe** [comment]
Could also be that I had some free API credits and they expired when I created my ChatGPT account and they expired bc I didnt know of it. I can sign up again, no problem there... 
![image](https://github.com/0xacx/chatGPT-shell-cli/assets/3632672/a4fcdb34-8687-46b2-94cb-c4e7ba4a8e8b)

**Comment by thomashrabe** [comment]
yep, that was it... new account, got $5 free access...
