### ISSUE TITLE
Bug - fold: illegal width value when using pipe mode

### ISSUE THREAD

**Issue by 0xacx** [0xacx/chatGPT-shell-cli#107]
Reported on discord:

Running chatgpt in pipe mode:
`cat /test_playbook.yml | ./chatgpt.sh --init-prompt-from-file ../prompts/documentation_instructions_and_format.txt`
results in 
`fold: illegal width value`

Assumption: The $COLUMNS variable probably is not initialized or updated properly when using pipe mode.

**Comment by 0xacx** [comment]
Closing this as I cannot reproduce the error.

**Comment by mountaineerbr** [comment]
If this error is ever encountered again, a mitigation may be setting `shopt -s checkwinsize`.

Or a workaround `echo text | {    fold -s -w $COLUMNS 2>/dev/null || cat ;}`

**Comment by 0xacx** [comment]
@mountaineerbr thank you very much for the tips! 🙏 
I was not able to reproduce the error but the user had it again today, so I will give it another try.

**Comment by marzbana** [comment]
Did any of the fixes work? Im facing the same issue, thanks!

**Comment by camyujistark** [comment]
I was having a similar issue. Turns out when running with zsh shopt command is unknown. In my case, running chatgpt command with bash in front fixed the issue. `bash chatgpt <command>`

**Comment by marzbana** [comment]
Thanks so much! Also I figured out removing the column variables and that stuff fixed it for me as well
