### ISSUE TITLE
Your request to Open AI API failed: insufficient_quota

### ISSUE THREAD

**Issue by chandrahmuki** [0xacx/chatGPT-shell-cli#115]
i do have a chatgpt + account so i dont really understand what im doing wrong ? on OpenAI though it shows my account as personal ? 

Thanks for any help ..

**Comment by 0xacx** [comment]
@chandrahmuki Your free API credits have probably expired. Have you checked your OpenAI API usage at https://platform.openai.com/account/usage ?
