### ISSUE TITLE
changing openai api key not working

### ISSUE THREAD

**Issue by hadster2023** [0xacx/chatGPT-shell-cli#116]
hi, i am using chatgpt shell cli in termux , i have consumed quota of my api key , so i changed it with a new free api key in bash.bashrc. but i am still getting this error "Your request to Open AI API failed: insufficient_quota
You exceeded your current quota, please check your plan and billing details.". i am using chatgpt.sh i dont have root.

**Comment by 0xacx** [comment]
If you installed this with the installation script, then the key should be in `~/.profile` or `~/.bash_profile`, or `~/.zprofile` if you have zsh installed. So you should locate the `OPENAI_KEY=$your_old_key` in one of these files and replace it with your new key.  I think the default profile for Android is `~/.profile` so check there first. If you installed the script manually, then you should remember or find out where you set the key and replace it there. 

As a last resort, If you don't have root access to change profile files, then you could just set the key in the chatgpt.sh file by adding `OPENAI_KEY=$your_new_key` on top. Note that keeping secrets inside scripts is definitely not a good practice and I wouldn't recommend that.

**Comment by hadster2023** [comment]
i am using bash , i cant find the .profile or .bash_profile in home directory.In termux bash.bashrc is in /data/data/com.termux/files/usr/etc , i have an entry in it with export openai key , also i tried exporting key from commandline, tried  entering the key in chatgpt.sh as you said ,doesnt work.i believe chatgpt.sh is retaining the old key stored it somewhere.Thanks for a great script .

**Comment by hadster2023** [comment]
its probably a openai server thing because i tried , installing everything fresh , and exporting the new api key , still getting quota exceeded message.
