### ISSUE TITLE
The model: `gpt-4` does not exist"? I have just paid for it. 

### ISSUE THREAD

**Issue by JackDinn** [0xacx/chatGPT-shell-cli#123]
I have just paid for my ChatGPT Plus account but when i try "chatgpt --model gpt-4" and then type anything into the shell, It errors with "Your request to Open AI API failed: invalid_request_error
The model: `gpt-4` does not exist"

Im not sure how/what im supposed to do after paying for the subscription?

**Comment by 0xacx** [comment]
According to this [answer](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4) a ChatGPT Plus subscription does not include access to gpt-4 API. 

To get access to the gpt-4 API you should join the waiting list. 
Alternatively, you can submit an eval to [OpenAI/evals repository](https://github.com/openai/evals) and if it gets merged, you will get access.

**Comment by JackDinn** [comment]
Yes thx, iv just found out on discord from yourself :) , 

Although i have already submitted to the waiting list a long time ago (when it first became available) I never heard anything back. This was why i thought i would just pay for it, as i was tired of waiting. Now all i succeeded in doing was loosing money ^^ O well.

I do appreciate your help though :)
