### ISSUE TITLE
"open" is not working

### ISSUE THREAD

**Issue by goosegit11** [0xacx/chatGPT-shell-cli#26]
I see that this application is developed by a Mac user and for Mac users, so there's some problems with it running on GNU/Linux.
So in line 263 you have the command "open". 
In GNU/Linux there is no such command, but its counterpart is "xdg-open". 
You can easily make the script check the system and then use "xdg-open" or "open" depending on the system.

**Comment by 0xacx** [comment]
This issue has been addressed in #33
