### ISSUE TITLE
Newlines are not saved in history 

### ISSUE THREAD

**Issue by edshamis** [0xacx/chatGPT-shell-cli#41]
❯ ./repos/bin/chatGPT-shell-cli/chatgpt.sh
Welcome to chatgpt. You can quit with 'exit'.

Enter a prompt:
write any python function

chatgpt Here's an example of a Python function that takes two arguments (a and b) and returns their sum:

```
def add_numbers(a, b):
    sum = a + b
    return sum
```

Once defined, you can call this function with two numbers as arguments:

```
result = add_numbers(5, 7)
print(result)
```

This would output `12` because the function adds 5 and 7 together.

Enter a prompt:
history

16/03/2023 20:58 write any python function
Here's an example of a Python function that takes two arguments (a and b) and returns their sum:  ``` def add_numbers(a, b):     sum = a + b     return sum ```  Once defined, you can call this function with two numbers as arguments:  ``` result = add_numbers(5, 7) print(result) ```  This would output `12` because the function adds 5 and 7 together.

**Comment by mountaineerbr** [comment]
Input and new lines can be escaped always when necessary with something like:

```
function escapef
{
	typeset var
	var="${*%%*([$IFS])}" var="${var##*([$IFS])}"
 	var=${var//[\"]/\\\"}          #double quote marks
	var=${var//[$'\t']/\\t}        #tabs
	var=${var//[$'\n\r\v\f']/\\n}  #new line/form feed
 	var=${var//\\\\[\"]/\\\"}      #rm excess escapes
 	var=${var//\\\\[n]/\\n}
 	var=${var//\\\\[t]/\\t}
	printf '%s\n' "$var"
}

function unescapef
{
	typeset var
 	var=${*//\\\"/\"}
	var=${var//\\t/$'\t'}
	var=${var//\\n/$'\n'}
	printf '%s\n' "$var"
}
```

Cheers!
