### ISSUE TITLE
Init prompt error

### ISSUE THREAD

**Issue by ecsplendid** [0xacx/chatGPT-shell-cli#45]
I get this

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/6911390/226174180-d73ddedf-a1ea-4096-a8b4-b3492a90aaf0.png">

**Comment by 0xacx** [comment]
This must have been fixed with this PR https://github.com/0xacx/chatGPT-shell-cli/pull/106
@ecsplendid If you could confirm you are not facing this issue anymore it would be great 👍
