### ISSUE TITLE
AUR package needed

### ISSUE THREAD

**Issue by Zeioth** [0xacx/chatGPT-shell-cli#47]
A similar project ([gpt-chatbot-cli](https://github.com/slithery0/gpt-chatbot-cli)) is on the AUR. But not this one.

**Comment by Zeioth** [comment]
I've created the AUR package myself: https://aur.archlinux.org/packages/chatgpt-shell-cli-git
If anyone want to test it, please write here any issue you may find.

[I'm only copying the file chatgpt.sh to /usr/local/bin/chatgpt](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chatgpt-shell-cli-git), which seems to be the bare minimum to have it working.

**Comment by Zeioth** [comment]
I've also created an [stable AUR package](https://aur.archlinux.org/packages/chatgpt-shell-cli), pointing to main's current head, so we can keep experimenting safely on -git package.

**Comment by se7en-x230** [comment]
Installed the git version and it doesn't change open to xdg-open for images

**Comment by Zeioth** [comment]
Also I don't currently own gpt4 so I cannot test is we have sixel support, which is the standard for displaying graphics on terminal (supported by foot, and other modern terminals)

**Comment by 0xacx** [comment]
@Zeioth Thank you very much for submitting the AUR package! 🙏 
Do you think there's a way to perform the substitution of `open` to `xdg-open` in the PKGBUILD file?

**Comment by Zeioth** [comment]
@0xacx after double checking it I understand that sed command is actually making a substitution in the chatgpt script. Ok I just added the change, [you can check it out here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-command-gpt-git).

**Comment by 0xacx** [comment]
@Zeioth That is awesome! 🔥  
I think you can remove the ` if [[ "$OSTYPE" == "linux-gnu"* ]] || [[ "$OSTYPE" == "freebsd"* ]]; then` and closing `fi` because AUR packages would only run on Linux. What do you think?
I can't test it on my mac, but does it run correctly on your machine?
@se7en-x230 could you please re-install and confirm that it works as expected?

Thank you both very much! This is greatly appreciated 🙏

**Comment by Zeioth** [comment]
That's a good point. [I removed the if condition](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chatgpt-shell-cli-git). Also now we install the LICENSE file in the right directory.

I just reinstalled it after clearing cache and still works fine. 
Please feel free to double check!

**Comment by Zeioth** [comment]
Consider adding the arch linux installation method to the README

    paru -S chatgpt-shell-cli

**Comment by 0xacx** [comment]
Great! 👍  
One last thing, the license file wouldn't need execute permissions since it's not an executable file. So just read and write for the owner and read for anyone else I think would be a bit better (replace with -Dm644). 

Does installation work with `pacman` package manager as well?

**Comment by 0xacx** [comment]
Ok, right! Thanks for the work on PKGBUILD! 
I think we can call this done now and close this issue! 🎉 ✌️

**Comment by se7en-x230** [comment]
> @Zeioth That is awesome! 🔥 I think you can remove the ` if [[ "$OSTYPE" == "linux-gnu"* ]] || [[ "$OSTYPE" == "freebsd"* ]]; then` and closing `fi` because AUR packages would only run on Linux. What do you think? I can't test it on my mac, but does it run correctly on your machine? @se7en-x230 could you please re-install and confirm that it works as expected?
> 
> Thank you both very much! This is greatly appreciated 🙏

![shop-2023-03-21-11-49](https://user-images.githubusercontent.com/69777713/226521256-7fbdd22d-2732-4290-9f38-23bfd6d04594.png)

works
