### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by halpz** [0xacx/chatGPT-shell-cli#51]
here is my terminal output:

```
paul@laptop ~ % curl -sS https://raw.githubusercontent.com/0xacx/chatGPT-shell-cli/main/install.sh | sudo -E bash
Password:
zsh: done                   curl -sS  | 
zsh: suspended (tty input)  sudo -E bash
paul@laptop ~ % 
```

**Comment by halpz** [comment]
is this a zshell issue?

**Comment by Zeioth** [comment]
@halpz If you are on arch linux, now you have this two packages:

    paru -S chatgpt-shell-cli
    paru -S chatgpt-shell-cli-git

**Comment by earthpyy** [comment]
I'm having the same problem on macOS M2, zsh shell.  
![CleanShot 2566-03-23 at 22 03 19](https://user-images.githubusercontent.com/5132475/227247907-c039c253-4062-4504-9d13-f8322c4be70c.png)

Saving the install script as a file first, then run it using `sudo -E bash ./install.sh` works.
