### ISSUE TITLE
Proposal: Avoid passing the API KEY as ENV VAR

### ISSUE THREAD

**Issue by Zeioth** [0xacx/chatGPT-shell-cli#54]
**PROBLEM**
Defining OPENAI_KEY as an env var, makes your chatgpt KEY available to any program. 

**SOLUTION**
If instead we store the key in ~/chatgpt-shell-cli.apikey, the user will be able to manage file permissions.

Optionally, having a --update-key options could be a user friendly way to set the api key.

**Comment by 0xacx** [comment]
@Zeioth I left a comment to respond to the same issue in https://github.com/0xacx/chatGPT-shell-cli/issues/55 so I am closing this and the discussion can continue there. Thank you for the suggestion!
