### ISSUE TITLE
Not a bug, just showing off

### ISSUE THREAD

**Issue by Zeioth** [0xacx/chatGPT-shell-cli#56]
It works correctly on Termux, on Android. I manually installed chatgpt.sh on ~/.local/bin and added the path to .bashrc or .zshrc
![Screenshot_20230322_023547_Termux](https://user-images.githubusercontent.com/3357792/226781521-77860b84-d925-4593-9baf-4af53e93802f.jpg)

**Comment by 0xacx** [comment]
Good to know! 👍
