### ISSUE TITLE
root requirement

### ISSUE THREAD

**Issue by matbee-eth** [0xacx/chatGPT-shell-cli#57]
Why is root needed?
Would be best to stick to user space and request the user to add PATH to bash_profile

**Comment by Zeioth** [comment]
On most of my AUR packages people are divided with the same question. So here I am documenting about it again, and [the AUR guidelines](https://wiki.archlinux.org/title/Arch_package_guidelines) advise not to install packages in /usr/local/.

People on #Archlinux IRC redirected me [here](https://wiki.archlinux.org/title/Arch_package_guidelines#Directories), so the convention is actually to install on /usr/bin. And it specifically says, packages should not modify the /home directory (where .local/bin is).

Also, in case you want to make a program available only for certain users, the right way is to do it through user permissions, not through ~/.local/bin, this directory is for user scripts only.

**Comment by Zeioth** [comment]
In other words, root is always required when you install a program.

**Comment by matbee-eth** [comment]
Yeah, I'll just fork and put it in npm or such
