### ISSUE TITLE
Table output support is not very good, hope it can be optimized

### ISSUE THREAD

**Issue by 191338780** [0xacx/chatGPT-shell-cli#62]
Table output support is not very good, hope it can be optimized

| 咖啡种类 | 咖啡 | 牛奶 | 糖 | 其他 |
| --- | --- | --- | --- | --- |
| 拿铁 | 浓缩咖啡 | 牛奶 | 可选 | - |
| 卡布奇诺 | 浓缩咖啡 | 牛奶 | 可选 | 泡沫奶 |
| 美式咖啡 | 浓缩咖啡 | 可选 | 可选 | - |
| 摩卡咖啡 | 浓缩咖啡 | 牛奶 | 巧克力 | - |
| 香草拿铁 | 浓缩咖啡 | 牛奶 | 香草糖浆 | - |
| 卡布奇诺玛奇朵 | 浓缩咖啡 | 牛奶 | 可选 | 一层巧克力酱和泡沫奶 |
| 冰咖啡 | 浓缩咖啡 | 可选 | 可选 | 冰块 |
| 浓缩咖啡 | 浓缩咖啡 | 可选 | 可选 | - |

注意，这个表格只是一个示例，并不代表所有咖啡店都会使用相同的成分。成分可能因品牌、制作方式、地区和个人口味而异。

**Comment by 0xacx** [comment]
I am planning to add markdown rendering at some point, that will hopefully help with tables.

**Comment by 0xacx** [comment]
I just merged a PR that adds support for markdown, which greatly improves table rendering. You need to install [glow](https://github.com/charmbracelet/glow) for this to work. Even though this doesn't render 100% perfect, it is a big improvement from the previous output.

I am closing this issue as done. Please let me know if you face any issues.
