### ISSUE TITLE
Installation improvments: Add .zshrc to install script, avoid overwriting $PATH if /usr/local/bin already found

### ISSUE THREAD

**Issue by emirkmo** [0xacx/chatGPT-shell-cli#65]
I made two PRs to solve issues I ran into while installing on my machine. Basically, the install script does not check for .zshrc, which is actually the place to put anything related to interactive sessions, such as this package. I do not have a .zprofile on m debian machine, and this is common.

I also did not want /usr/local/bin prepended to my path. It is already therem but is located after `conda` / `mambaforge` bin for virtual environment purposes, which is the standard conda install. So the install script should not prepend it.

I made two PRs that solve the issues. #63 and #64

Hope they are useful. Let me know if you have any questions.

**Comment by Zeioth** [comment]
What distro are you on? install.sh work, but it is more like a reference script. Ideally we should have a package per distro, like the one we already have for arch. A pip package to install it easily is also WIP right now.

In those, .profile and path won't be modified.

**Comment by 0xacx** [comment]
Both PRs are addressed so this issue is done! 👍
