### ISSUE TITLE
Any idea what actually makes AI reply here different to official homepage site

### ISSUE THREAD

**Issue by abdulbadii** [0xacx/chatGPT-shell-cli#66]
Any idea why AI reply here different to official homepage `https://chat.openai.com/chat` , what actually makes it so and how to obtain the one in that site?

**Comment by 0xacx** [comment]
The site `https://chat.openai.com/chat` is probably running `gpt-4` while the script is using the `gpt-3.5-turbo` as the `gpt-4` api is not open to everyone, but only for subscribers and people who got early access. If you have access to `gpt-4` you can set the model it in the script and use it. 
When you visit the site you can check in the bottom what version is running: https://help.openai.com/en/articles/6825453-chatgpt-release-notes
