### ISSUE TITLE
Multi-line input in interactive mode

### ISSUE THREAD

**Issue by ciaran-matthew-dunne** [0xacx/chatGPT-shell-cli#69]
Currently, interactive mode only allows for single-line input. This can be
inconvenient when working with longer prompts, especially when copy/pasting code blocks from a code editor. Therefore, I suggest considering allowing multi-line input in interactive mode, perhaps by a distinction between Enter and Shift+Enter.

I believe this enhancement would make the CLI more user-friendly.
Thank you for your consideration.

Ciaran

**Comment by camAtGitHub** [comment]
Implemented here on this pull request: https://github.com/0xacx/chatGPT-shell-cli/pull/90 
I tried to keep it simple with native tooling....
