### ISSUE TITLE
LaTeX doesn't work well with shell.

### ISSUE THREAD

**Issue by aaaaaQIE** [0xacx/chatGPT-shell-cli#70]
When chatGPT replies mathematical expression in $\LaTeX$ , some symbles will be transferred to what I don't want. Mainly due to it functioning as an escape character.

### 1. The missing "\f"

Enter a prompt:
What is the Maclaurin formula of $\arcsin x$ ?

_chatgpt_ The Maclaurin series formula for $arcsin(x)$ is:

$arcsin(x)=\sum_{n=0}^{\infty} 
                               rac{(2n)!}{4^n(n!)^2(2n+1)}x^{2n+1}$

> While "\frac" is the correct response.

### 2. The missing "\t"

Enter a prompt:
$\theta=3x+2$ ,what is $x$?

_chatgpt_ Without additional information or an equation to solve for a specific value of $heta$, it is not possible to determine the value of $x$ from the given equation $	heta = 3x + 2$.

> While "\theta" is the correct response.

Additionally, I tried to make chatGPT answer in single quotation marks. But that does not work at all either.

**Comment by mountaineerbr** [comment]
The `read command` is set as `read -e` in this script. In this case, try typing `\\f` for **\\f** and `\\theta` for **\\theta**. However, do note that when this is read in json syntax, `\t` will mean `<TAB>`, so maybe you will need to escape the backslash with something like `\\\\theta` (as in the following case of pos arg input).

If `read -e -r` were set, then typing a single backslash would work.

Note that however if `-p "[prompt]"` is set from pos args, then it will _probably_ not matter if you type either `"\\f"` or `"\f"`, or `'\f'` for **\\f** symbol.

**Comment by aaaaaQIE** [comment]
Everything fixed after installing `glow` .
