### ISSUE TITLE
Cannot login to OpenAI

### ISSUE THREAD

**Issue by erasmus74** [0xacx/chatGPT-shell-cli#71]
```
❯ chatgpt

             Provide a prompt for ChatGPT, or type /help or ? to list commands.

1> /login
Enter username or email: xxxxxxxx@xxxxxxx.com
AttributeError("'NoneType' object has no attribute 'password'")```
1>
```

Obviously I'm trying to use it, tried installing from AUR and from pip. 

uname -a:
```
Linux mjolnir 6.2.8-zen1-1-zen
```
python version
```
❯ python --version
Python 3.10.10
```
zsh shell.

**Comment by 0xacx** [comment]
You must be using a different script. This script is written in shell, does not use python and does not have a pip package currently. Also the chat interface is different. I think you should create this issue in a different repo. I am closing this issue as it is not relevant to this repo.
