### ISSUE TITLE
insufficient_quota

### ISSUE THREAD

**Issue by improve100** [0xacx/chatGPT-shell-cli#82]
$ chatgpt
Welcome to chatgpt. You can quit with 'exit'.

Enter a prompt:
hello
Your request to Open AI API failed: insufficient_quota
You exceeded your current quota, please check your plan and billing details.

**Comment by 0xacx** [comment]
Well, as the message says "You exceeded your current quota, please check your plan and billing details.". Have you checked your OpenAI API usage?

**Comment by improve100** [comment]
![image](https://user-images.githubusercontent.com/6092914/231180547-e12b4e76-5e92-4b0d-b422-0ff4e2bbd51e.png)

**Comment by 0xacx** [comment]
Your free trial has expired on April 1st.

**Comment by cgumb** [comment]
It is my understanding that chatgpt+ does not actually give you access to gpt-4 via the API.
So if you have chatgpt+ account, but have not set up a payment method for API calls specifically, when you create an API token its use will always result in these "insufficient quota" errors.

But even if you then go and fill in payment info for API calls you _still_ won't have access to gpt-4 via the API.

Their marketing is a bit screwed as I imagine most people who pay for ChatGPT Plus are assuming that $20 a month actually gives them access to GPT4.
