### ISSUE TITLE
I have a few of these errors. Am I using a character that I'm supposed to escape or something? If so, which one?

### ISSUE THREAD

**Issue by JackDinn** [0xacx/chatGPT-shell-cli#94]
```
❱chat
Welcome to chatgpt. You can quit with 'exit' or 'q'.

Enter a prompt:
in bash how do you split a long line


chatgpt

In Bash, you can split a long line by using the backslash (\) character at the end of a line to indicate that the
command continues on the next line. Alternatively, you can use parentheses () or curly braces {} to group commands
together and split them onto multiple lines.


Enter a prompt:
demonstrate

Your request to Open AI API failed: invalid_request_error
We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what wassent was not valid JSON. If you have trouble figuring out how to fix this, please send an email to support@openai.com and include any relevant code you'd like help with.)
1

❱chat
Welcome to chatgpt. You can quit with 'exit' or 'q'.

Enter a prompt:
in bash how do you split a long line


chatgpt

In Bash, you can split a long line using the backslash (\) character at the end of the line, indicating that the
command continues on the next line. For example:

echo "This is a very long \
line that needs to be split \
into multiple lines for clarity."

Alternatively, you can also use parentheses to group commands and split them across multiple lines. For example:

( command1 arg1 arg2 \
&& command2 arg1 arg2 \
&& command3 arg1 arg2 )


Enter a prompt:
"can you use parentheses () or curly braces {} to group commands together and split them onto multiple lines? if so please demonstrate."

Your request to Open AI API failed: invalid_request_error
We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what wassent was not valid JSON. If you have trouble figuring out how to fix this, please send an email to support@openai.com and include any relevant code you'd like help with.)
1
```

**Comment by JackDinn** [comment]
well thats kinda what i always thought about the AUR's that point to git but I'm never sure.

The AUR says it was last updated  2023-03-31 11:10 (UTC) so ... i don't know. Im sure i could just download your code and use it directly just to test, but iv got some of my own code that is using it from the AUR binary. I don't want to get in a muddle and mess up what iv got.

**Comment by 0xacx** [comment]
I don't think you need to download the code. If you just reinstalled with `paru -S chatgpt-shell-cli` I think it should work 🤞
The last updated timestamp on AUR probably refers to the changes made in the AUR file itself. 
But yes, you know your setup better. I am just curious if the changes are available immediately in the AUR.

**Comment by Zeioth** [comment]
Try also chatgpt-shell-cli-git.That one is 1:1 with this repo.

**Comment by JackDinn** [comment]
No, as far as i can tell it still does that same. I have removed chatgpt-shell-cli-git and installed chatgpt-shell-cli ver 0.2.2
```
2 aur/chatgpt-shell-cli-git 1.0.r161.ea41590-2 (+1 0.43)
Use OpenAI's ChatGPT and DALL-E from the terminal.
1 aur/chatgpt-shell-cli 0.2-2 (+3 1.77) (Installed)
Use OpenAI's ChatGPT and DALL-E from the terminal.
```

But unfortunately it still does exactly the same

```
❱chat
Welcome to chatgpt. You can quit with 'exit' or 'q'.

Enter a prompt:
in bash how do you split a long line

chatgpt In Bash, you can split a long line using the backslash character "\" at the end of the line to indicate that the command continues on the next line. For example:


echo "This is a very long \
line of text that needs to \
be split into multiple lines."


This will output the following on a single line:


This is a very long line of text that needs to be split into multiple lines.


Enter a prompt:
demonstrate
Your request to Open AI API failed: invalid_request_error
We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what wassent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)
1

```

**Comment by JackDinn** [comment]
Does your not do the same if you use the exact same prompts?

1st prompt :- "in bash how do you split a long line"
2nd prompt :- "demonstrate"

Everything else works fine for me but these two particular prompts throw this error.

**Comment by JackDinn** [comment]
well i pass. I have glow as well ^^

I did notice there is no chatgpt --version ?

Its not important to me as it was just something i stumbled across when i was testing. It's not something i'd ever come across again (i hope). I use it every day without any problems, so i really can't help.

**Comment by 0xacx** [comment]
No there is no --version. So far all changes are backwards compatible, meaning we never broke something to add something new. What you get from the repo is always the latest version. 
Adding versioning would mean that it would require some version and release management and I think this is really not worth it for a simple one file script. But if in the future we need to add breaking changes then we would have to use versions to differentiate.

**Comment by JackDinn** [comment]
Unless it has something to do with the fact that I use FISH, I can't see how. Other than that, I would have to use your open code, look at the JSON as it's created, and figure out what's going on before it's attempted to be sent. But I'm busy with stuff :).

**Comment by JackDinn** [comment]
Ok, it was making me scratch my head. I removed all versions (the CLI, CLI- Git, and the Git folder where I had it cloned). Basically, I removed every remnant of it. I rebooted the system and reinstalled ChatGPT-Shell-CLI from the AUR, and it's working! :woozy_face:

Don't ask, but it looks like it was a "me" problem. 

Thx for your help :smile:
